Adds example for GameObject property bindings
JochenHeckl/DataBinding pull request #28
Opened 2024-08-09 13:35 UTC by JochenHeckl

2024-08-10 10:12 UTC, benedikt-peter requested changes

2024-08-10 10:12 UTC, benedikt-peter commented on Runtime/Scripts/GameObjectPropertyBindings.cs
I'd suggest to add another property here for the GameObject's name.

2024-08-13 14:58 UTC, JochenHeckl commented on Runtime/Scripts/GameObjectPropertyBindings.cs
My bad. I added name as we discussed

2024-08-13 15:38 UTC, benedikt-peter commented on Runtime/Scripts/GameObjectPropertyBindings.cs
I think it should be string instead of int.

2024-08-13 16:11 UTC, JochenHeckl commented on Runtime/Scripts/GameObjectPropertyBindings.cs
and you are right!

2024-08-13 16:20 UTC, benedikt-peter approved these changes

2024-08-13 16:49 UTC, benedikt-peter approved these changes

2024-08-14 06:12 UTC, merged